### ISSUE TITLE
Exception generate trying to mount pet

### ISSUE THREAD

**Issue by TheWebbe** [AlexandreChaussard/AdvancedPet#5]
I tried to join the Discord server linked on the spigot page, but the link is invalid. 

I am getting an exception when trying to mount a pet via the GUI

```
[06:01:36 ERROR]: Could not pass event InventoryClickEvent to AdvancedPet v1.0.3
java.lang.NoSuchMethodError: 'com.ticxo.modelengine.api.mount.handler.IMountHandler com.ticxo.modelengine.api.model.ModeledEntity.getMountHandler()'
        at fr.nocsy.almpet.data.Pet.setMount(Pet.java:610) ~[AdvancedPet r1.0.5.jar:?]
        at fr.nocsy.almpet.listeners.PetInteractionMenuListener.mount(PetInteractionMenuListener.java:154) ~[AdvancedPet r1.0.5.jar:?]
        at fr.nocsy.almpet.listeners.PetInteractionMenuListener.click(PetInteractionMenuListener.java:72) ~[AdvancedPet r1.0.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor40.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-108]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2817) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-108]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-108]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-108]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-108]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-108]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.18.1.jar:git-Paper-108]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-108]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-108]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Versions: 
Server - Paper 1.18.1 Build 108
ModelEngine - r2.3.1 (Paid Version)
MythicMobs - 4.14.1
AdvancedPet - r1.0.5

I'm using [this](https://mcmodels.net/model/mexbots-savanna-pack/) mob pack which shows it should be mountable (mount shows up in the GUI)

**Comment by TheWebbe** [comment]
This was due to incompatible ModelEngine version. r1.0.6 fixes this.
